/**
 * The bundled skills, carried INSIDE agent.cjs — generated by `scripts/bundle.mjs` for the
 * release build and restored to this empty placeholder afterwards.
 *
 * Why they ride with the agent and not only in the sidecar tree: a routine update replaces
 * `agent.cjs` (a few MB) and leaves the sidecar tree alone, because the tree is 140 MB of
 * pinned binaries that change twice a year. The skills live in that tree — and change as often
 * as the agent does. Without this, a rewritten skill would reach nobody until the next time a
 * vendored binary moved. So the agent carries them, and on start it writes them beside itself
 * when the stamp there is not its own (`skills.ts`, `materializeEmbeddedSkills`).
 *
 * `stamp` is a hash of the files; `files` maps `skill/relative/path` to base64 content. Empty
 * here, which means "nothing to write" — a checkout reads `core/skills` directly.
 */
export const EMBEDDED_SKILLS: { stamp: string; files: Record<string, string> } = { stamp: '', files: {} }
